{% set version = "2.4.0" %}

package:
  name: arpackpp
  version: {{ version }}

source:
  fn: arpackpp-{{ version }}.tar.gz
  url: https://github.com/m-reuter/arpackpp/archive/{{ version }}.tar.gz
  sha256: 06416ee584d01eba42555b676a4220f68575ef715cde9b37e85910698d784ca0

build:
  number: 0
  skip: true  # [win]
  script:
    - install -d ${PREFIX}/include/arpack++
    - install include/*.h ${PREFIX}/include/arpack++

requirements:
  run:
    - arpack

test:
  commands:
    - test -f ${PREFIX}/include/arpack++/arpackf.h

about:
  home: http://reuter.mit.edu/software/arpackpatch/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: an object-oriented version of the ARPACK package

extra:
  recipe-maintainers:
    - jschueller
