travis:
  secure:
    BINSTAR_TOKEN: VqTYwQG21czvTioow06AC7gx1arZJxlvageeWbzt52HN/b5Ekvr9wea9IrRsuBFcogASj8BVBiSdcDy60e9C9IH4cteYCdiu1UmKucHBR8d7On+JZS9AINYWrVhtXBwaepqFXCBGzPHj375tI9Q9tb4WusKrJBuRNYCkgbPQm/G9LPdhcvPlTz3RABYziAyyDuJfYVGf/q4YwgnRxn37trH2dMO+OLAOvihiLdMOEgK12AehyMfMYRqk3rPA0DGWPswAmVlwD1J/+VPi+FAZZFwihUWxVq+3Ky3451E+M2tOYNPlR9sx/Iy6OQC0IhKOSi6bTf/vWFzs9NT38vRVnXpa3/Y0Q8/GPvrmVsPzGQmAvQP1qsdyinje4thDVoCHw2SzjEEqxoD7O3G4T5i7wTrNfNniFpO7HBiUgNvIU0WjHpVmFBV0Vn5ONbAIFNcUwpzkqaaz32/igoZ2cu6faWWUwNt5Ok7rbkoJC/Uw1BdUOj/aTM+9qxrUMKtBVGyyLpMhvw9lR1YPMVbYx7DD9BqKA7NQe1q+9jeDGyzOcvHLJ3xwfPEfGsssau8wSuKrBqF/aGCZcVhdI5xi2JobskXkuNfTTVNv64PW3XX1cStgvOh6/QJOGr4lhzkLjsHsaYr0xcTJJS7rI7gnFR9735YzQZTngBfolKVT0NXI3HU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
