travis:
  secure:
    BINSTAR_TOKEN: HmWdKgOaKohMJ2qPTMFaLzwoJ+SFfFGbUipc5AssbHqrG7Pq0j/qnd9L8g4PmSWTjAwIGVS3F4D2f5ZUA7ZQ9m2L30QhE1ACIcd/P/3qXoCVvO3Zl3wmKN0Z4MnZ+32yrZ6unU/e/fH2A3lwDD/5hHvf7aC182DRNBvhJnw9tq6olkVYvD6VjVg0nmnyDGv/vc4ZZGMf05254xJZK6Rz18EqoqLfpFJb9fLZmUf+mZQ1ok6Pb+TA4Z6pB6uYD/E37ruGqqAcAClckzGkX9NcTZiiV3bAcd3E2ew37DWAz+chnTfdvpA10o/K4bXbNtfqc/9lnK0Xie/ddq31n6CeQUHkWHjraAtac7pR90ueS/sEC4bGVsZW7VsI+wUdBBoV+Nvkxs2FSYagm+Yj6z+kPysXar1yp1KIu/OJyBIVCSC79Tdk4LJrQpQs0X0WypauLQXvHjGDVVTkTsiYF7abYzDPoFVWJU41TZXNahdTFxQMq7V4pDJwSoQl6gXFssvtcfpGATx1ovoJ41O2zbB8YOHsraGAUSUafkq6H59EO7pqr4GWLegF/U/eCQUTYJfSbiJLxoSuN+7+XNYHuIXViDaJKDzkg/hbaPfC9RfPlt3lsoa1s6Ovds07pkxE6QAekRWttuy0jxLeu/3Muhed6wyMiT0nlCKdZi7yC/Qw3d8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
